export type Category = 'Football' | 'Amour' | 'Film d\'horreur' | 'Perso' | 'Argent' | 'Loyauté' | 'Style' | 'Maison' | 'Vices' | 'Talents' | 'Basket';

export interface Question {
  id: number;
  text: string;
  category: Category;
}

export const ALL_QUESTIONS: Question[] = [
  { id: 1, text: "Qui est le plus probable de forcer un geste technique et le rater lamentablement ?", category: 'Football' },
  { id: 2, text: "Qui serait le plus content que sa meuf le trompe ?", category: 'Amour' },
  { id: 3, text: "Qui mourrait en premier dans un film d'horreur ?", category: 'Film d\'horreur' },
  { id: 4, text: "Qui a le meilleur football avec les go ?", category: 'Football' },
  { id: 5, text: "Qui pleure le plus facilement pendant un film ?", category: 'Perso' },
  { id: 6, text: "Qui irait se réfugier chez les autres en cas de rupture à 3h du matin ?", category: 'Amour' },
  { id: 7, text: "Qui survivrait le plus longtemps dans un film d'horreur ?", category: 'Film d\'horreur' },
  { id: 8, text: "Qui rate le plus de penalties ?", category: 'Football' },
  { id: 9, text: "Qui dépenserait tout son argent en une semaine si on lui donnait 1 million ?", category: 'Argent' },
  { id: 10, text: "Qui est le plus susceptible de tomber amoureux d'une inconnue sur Instagram ?", category: 'Amour' },
  { id: 11, text: "Qui irait investiguer le bruit bizarre au lieu de fuir ?", category: 'Film d\'horreur' },
  { id: 12, text: "Qui célèbre le plus théâtralement après un but ?", category: 'Football' },
  { id: 13, text: "Qui emprunte de l'argent sans jamais rembourser ?", category: 'Argent' },
  { id: 14, text: "Qui est le plus fidèle en couple ?", category: 'Loyauté' },
  { id: 15, text: "Qui serait le premier sacrifié par le groupe pour survivre ?", category: 'Film d\'horreur' },
  { id: 16, text: "Qui se plaint le plus de l'arbitre ?", category: 'Football' },
  { id: 17, text: "Qui ferait faillite en moins d'un an si on lui donnait une entreprise ?", category: 'Argent' },
  { id: 18, text: "Qui est le plus probable de stalker son ex sur les réseaux ?", category: 'Amour' },
  { id: 19, text: "Qui serait le traître dans un film de survie ?", category: 'Film d\'horreur' },
  { id: 20, text: "Qui dribble le plus mais ne tire jamais ?", category: 'Football' },
  { id: 21, text: "Qui vivrait au jour le jour sans jamais épargner ?", category: 'Argent' },
  { id: 22, text: "Qui resterait avec quelqu'un rien que par pitié ?", category: 'Loyauté' },
  { id: 23, text: "Qui crierait le plus fort dans une maison hantée ?", category: 'Film d\'horreur' },
  { id: 24, text: "Qui conteste le plus les décisions de l'arbitre ?", category: 'Football' },
  { id: 25, text: "Qui ferait un crédit pour acheter des sneakers ?", category: 'Argent' },
  { id: 26, text: "Qui tomberait amoureux le plus vite ?", category: 'Amour' },
  { id: 27, text: "Qui serait le héros inattendu dans un film d'horreur ?", category: 'Film d\'horreur' },
  { id: 28, text: "Qui joue le plus perso sur le terrain ?", category: 'Football' },
  { id: 29, text: "Qui inviterait tout le monde au restau mais oublierait son portefeuille ?", category: 'Argent' },
  { id: 30, text: "Qui pardonne le plus facilement une trahison ?", category: 'Loyauté' },
  { id: 31, text: "Qui glisserait sur quelque chose au mauvais moment dans un film d'horreur ?", category: 'Film d\'horreur' },
  { id: 32, text: "Qui marque un but et regarde l'équipe adverse au lieu de célébrer ?", category: 'Football' },
  { id: 33, text: "Qui payerait l'addition pour impressionner mais pleure après chez lui ?", category: 'Argent' },
  { id: 34, text: "Qui enverrait un texto à son ex à minuit ?", category: 'Amour' },
  { id: 35, text: "Qui serait possédé par le démon en premier ?", category: 'Film d\'horreur' },
  { id: 36, text: "Qui joue gardien même s'il déteste ça ?", category: 'Football' },
  { id: 37, text: "Qui revend ses cadeaux sur leboncoin ?", category: 'Argent' },
  { id: 38, text: "Qui garderait un secret pendant des années ?", category: 'Loyauté' },
  { id: 39, text: "Qui ouvrirait la porte interdite dans le film ?", category: 'Film d\'horreur' },
  { id: 40, text: "Qui insulte le plus l'adversaire après un tacle ?", category: 'Football' },
  { id: 41, text: "Qui a le plus de dettes cachées ?", category: 'Argent' },
  { id: 42, text: "Qui présente sa meuf à ses parents après seulement 1 semaine ?", category: 'Amour' },
  { id: 43, text: "Qui survivrait grâce à une cachette ridicule ?", category: 'Film d\'horreur' },
  { id: 44, text: "Qui regarde plus ses chaussures que le ballon ?", category: 'Football' },
  { id: 45, text: "Qui achète des trucs inutiles juste parce que c'est en solde ?", category: 'Argent' },
  { id: 46, text: "Qui est le plus probable de se faire 'friendzoner' ?", category: 'Amour' },
  { id: 47, text: "Qui ferait un pacte avec le tueur pour rester en vie ?", category: 'Film d\'horreur' },
  { id: 48, text: "Qui demande un changement après 5 minutes de jeu ?", category: 'Football' },
  { id: 49, text: "Qui ne sait pas dire non quand un vendeur lui propose un truc ?", category: 'Argent' },
  { id: 50, text: "Qui est le plus probable de se marier avec son premier amour ?", category: 'Amour' },
  { id: 51, text: "Qui oublierait de charger son téléphone juste avant le début du film d'horreur ?", category: 'Film d\'horreur' },
  { id: 52, text: "Qui met les crampons les plus chers mais joue le moins bien ?", category: 'Football' },
  { id: 53, text: "Qui demande toujours 'tu me rembourses quand ?' pour 1 euro ?", category: 'Argent' },
  { id: 54, text: "Qui croit encore au coup de foudre au premier regard ?", category: 'Amour' },
  { id: 55, text: "Qui se sacrifierait héroïquement pour le groupe ?", category: 'Film d\'horreur' },
  { id: 56, text: "Qui simule une blessure pour ne pas avoir à défendre ?", category: 'Football' },
  { id: 57, text: "Qui a toujours une excuse pour ne pas payer sa part ?", category: 'Argent' },
  { id: 58, text: "Qui est le plus romantique en secret ?", category: 'Amour' },
  { id: 59, text: "Qui rirait nerveusement face au tueur ?", category: 'Film d\'horreur' },
  { id: 60, text: "Qui est le plus mauvais perdant au foot ?", category: 'Football' },
  { id: 61, text: "Qui économise chaque centime pour un gros projet ?", category: 'Argent' },
  { id: 62, text: "Qui donnerait une seconde chance après une tromperie ?", category: 'Amour' },
  { id: 63, text: "Qui trouverait l'arme du crime mais s'en servirait mal ?", category: 'Film d\'horreur' },
  { id: 64, text: "Qui ramène toujours le ballon mais décide de qui joue ?", category: 'Football' },
  { id: 65, text: "Qui est le plus probable de gagner au loto et de tout perdre en un mois ?", category: 'Argent' },
  { id: 66, text: "Qui ferait un discours de 20 minutes pour une rupture ?", category: 'Amour' },
  { id: 67, text: "Qui serait le premier à soupçonner le mauvais coupable ?", category: 'Film d\'horreur' },
  { id: 68, text: "Qui donne des conseils tactiques alors qu'il est sur le banc ?", category: 'Football' },
  { id: 69, text: "Qui demande une facture pour tout ce qu'il achète ?", category: 'Argent' },
  { id: 70, text: "Qui est le plus susceptible de sortir avec l'ex d'un ami ?", category: 'Loyauté' },
  { id: 71, text: "Qui ferait tomber ses lunettes/clés au pire moment ?", category: 'Film d\'horreur' },
  { id: 72, text: "Qui ne fait jamais de passe même face au but vide ?", category: 'Football' },
  { id: 73, text: "Qui vérifie son compte en banque 10 fois par jour ?", category: 'Argent' },
  { id: 74, text: "Qui est le plus jaloux en couple ?", category: 'Amour' },
  { id: 75, text: "Qui serait le 'final girl/boy' qui survit à la fin ?", category: 'Film d\'horreur' },
  { id: 76, text: "Qui arrive en retard au match et veut être titulaire ?", category: 'Football' },
  { id: 77, text: "Qui achète des vêtements de marque juste pour les photos ?", category: 'Style' },
  { id: 78, text: "Qui est le plus fidèle en amitié ?", category: 'Loyauté' },
  { id: 79, text: "Qui s'endormirait pendant le suspense d'un film d'horreur ?", category: 'Film d\'horreur' },
  { id: 80, text: "Qui essaye de dribbler toute l'équipe adverse tout seul ?", category: 'Football' },
  { id: 81, text: "Qui possède le plus de paires de chaussures inutilisées ?", category: 'Style' },
  { id: 82, text: "Qui raconte sa vie privée à des inconnus ?", category: 'Perso' },
  { id: 83, text: "Qui ferait un selfie avec le fantôme ?", category: 'Film d\'horreur' },
  { id: 84, text: "Qui oublie ses protège-tibias à chaque fois ?", category: 'Football' },
  { id: 85, text: "Qui s'habille le mieux pour aller acheter du pain ?", category: 'Style' },
  { id: 86, text: "Qui est le plus susceptible de mentir pour protéger un ami ?", category: 'Loyauté' },
  { id: 87, text: "Qui essayerait de raisonner le tueur avec de la psychologie ?", category: 'Film d\'horreur' },
  { id: 88, text: "Qui marque contre son camp et fait comme si de rien n'était ?", category: 'Football' },
  { id: 89, text: "Qui passe le plus de temps devant le miroir ?", category: 'Style' },
  { id: 90, text: "Qui est le plus rancunier après une dispute ?", category: 'Loyauté' },
  { id: 91, text: "Qui trouverait le moyen de se cacher dans un frigo ?", category: 'Film d\'horreur' },
  { id: 92, text: "Qui est le plus technique mais n'a aucun physique ?", category: 'Football' },
  { id: 93, text: "Qui critique le style des autres tout en étant mal habillé ?", category: 'Style' },
  { id: 94, text: "Qui est le plus probable de pleurer de joie devant un cadeau ?", category: 'Perso' },
  { id: 95, text: "Qui penserait que le film d'horreur est une caméra cachée ?", category: 'Film d\'horreur' },
  { id: 96, text: "Qui fait des tacles glissés dangereux en match amical ?", category: 'Football' },
  { id: 97, text: "Qui achète des vêtements trop petits en espérant maigrir ?", category: 'Style' },
  { id: 98, text: "Qui garde les secrets les plus lourds sans sourciller ?", category: 'Loyauté' },
  { id: 99, text: "Qui appellerait la police pour un bruit de vent ?", category: 'Film d\'horreur' },
  { id: 100, text: "Qui court le moins pendant tout le match ?", category: 'Football' },
  { id: 101, text: "Qui a le style le plus 'original' (bizarre) ?", category: 'Style' },
  { id: 102, text: "Qui est le plus susceptible de se vexer pour une blague ?", category: 'Perso' },
  { id: 103, text: "Qui essayerait de filmer le tueur pour TikTok ?", category: 'Film d\'horreur' },
  { id: 104, text: "Qui veut toujours tirer les coups francs mais les met en touche ?", category: 'Football' },
  { id: 105, text: "Qui porte des lunettes de soleil à l'intérieur ?", category: 'Style' },
  { id: 106, text: "Qui est le pilier émotionnel du groupe ?", category: 'Loyauté' },
  { id: 107, text: "Qui mourrait de peur avant même de voir le monstre ?", category: 'Film d\'horreur' },
  { id: 108, text: "Qui crie 'J'ai !' et rate le ballon de la tête ?", category: 'Football' },
  { id: 109, text: "Qui suit toutes les modes même les plus ridicules ?", category: 'Style' },
  { id: 110, text: "Qui est le plus probable de s'excuser auprès d'un objet qu'il a cogné ?", category: 'Perso' },
  { id: 111, text: "Qui survivrait uniquement par pure chance ?", category: 'Film d\'horreur' },
  { id: 112, text: "Qui demande la VAR pour un hors-jeu imaginaire ?", category: 'Football' },
  { id: 113, text: "Qui dépense plus en coiffure qu'en nourriture ?", category: 'Style' },
  { id: 114, text: "Qui ne trahirait jamais le groupe même sous la torture ?", category: 'Loyauté' },
  { id: 115, text: "Qui ferait une sieste au milieu du match ?", category: 'Football' },
  { id: 116, text: "Qui a le plus de vêtements qu'il n'a portés qu'une fois ?", category: 'Style' },
  { id: 117, text: "Qui est le plus probable de se perdre dans sa propre maison ?", category: 'Perso' },
  { id: 118, text: "Qui est le plus maniaque de la propreté ?", category: 'Maison' },
  { id: 119, text: "Qui laisserait traîner sa vaisselle pendant une semaine ?", category: 'Maison' },
  { id: 120, text: "Qui est le plus probable de mettre le feu en cuisinant des pâtes ?", category: 'Maison' },
  { id: 121, text: "Qui a l'appart le plus 'déco Pinterest' ?", category: 'Maison' },
  { id: 122, text: "Qui ne range jamais son lit ?", category: 'Maison' },
  { id: 123, text: "Qui est le plus hospitalier ?", category: 'Maison' },
  { id: 124, text: "Qui marcherait pieds nus partout chez lui ?", category: 'Maison' },
  { id: 125, text: "Qui a le plus de plantes mortes chez lui ?", category: 'Maison' },
  { id: 126, text: "Qui pourrait vivre dans un désordre total sans s'en rendre compte ?", category: 'Maison' },
  { id: 127, text: "Qui mangerait tout ce qu'il y a dans le frigo sans remplacer quoi que ce soit ?", category: 'Maison' },
  { id: 128, text: "Qui inviterait des inconnus chez lui à 2h du matin ?", category: 'Maison' },
  { id: 129, text: "Qui installerait une caméra de surveillance chez lui par paranoïa ?", category: 'Maison' },
  { id: 130, text: "Qui décorerait son appart façon Instagram mais ne rangerait jamais ?", category: 'Maison' },
  { id: 131, text: "Qui est le plus probable de perdre son téléphone en sortie ?", category: 'Vices' },
  { id: 132, text: "Qui est accro à trop regarder les gens sur les réseaux sans jamais poster ?", category: 'Vices' },
  { id: 133, text: "Qui ferait du shopping en ligne à 2h du matin et le regretterait au matin ?", category: 'Vices' },
  { id: 134, text: "Qui boirait le café de tout le groupe sans en faire d'autre ?", category: 'Vices' },
  { id: 135, text: "Qui serait le roi/reine du drama sans chercher à en créer ?", category: 'Vices' },
  { id: 136, text: "Qui serait le plus susceptible de finir dans une émission de télé-réalité ?", category: 'Talents' },
  { id: 137, text: "Qui serait le meilleur avocat si il/elle avait fait du droit ?", category: 'Talents' },
  { id: 138, text: "Qui est le plus probable d'écrire un livre un jour ?", category: 'Talents' },
  { id: 139, text: "Qui ferait le meilleur youtubeur/influenceur ?", category: 'Talents' },
  { id: 140, text: "Qui aurait le plus de followers si il/elle se lançait vraiment sur les réseaux ?", category: 'Talents' },
  { id: 141, text: "Qui serait le plus constant à l'entraînement toute l'année ?", category: 'Football' },
  { id: 142, text: "Qui joue le meilleur foot avec la gueule de bois ?", category: 'Football' },
  { id: 143, text: "Qui est le meilleur buteur du groupe ?", category: 'Football' },
  { id: 144, text: "Qui simule le plus les fautes ?", category: 'Football' },
  { id: 145, text: "Qui est le plus fort au basket ?", category: 'Basket' },
  { id: 146, text: "Qui est le meilleur pivot du groupe même sans l'avoir jamais pratiqué ?", category: 'Basket' },
  { id: 147, text: "Qui simule une faute comme dans la NBA ?", category: 'Basket' },
  { id: 148, text: "Qui est le plus probable de péter une cheville et continuer à jouer quand même ?", category: 'Basket' },
  { id: 149, text: "Qui ferait le meilleur coach de l'équipe ?", category: 'Football' },
];

export const getQuestionsForRound = (round: number) => {
  const total = ALL_QUESTIONS.length;
  const perRound = Math.floor(total / 3);
  
  if (round === 1) return ALL_QUESTIONS.slice(0, perRound);
  if (round === 2) return ALL_QUESTIONS.slice(perRound, perRound * 2);
  return ALL_QUESTIONS.slice(perRound * 2);
};

export const getQuestionsCountForRound = (round: number) => {
  return getQuestionsForRound(round).length;
};
